version: '3.9'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=kids_wallet
            - POSTGRES_PASSWORD=KidsWallet321!
        volumes:
            - ~/Docker/volumes/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - kids-wallet
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        ports:
            - 16543:80
        volumes:
            - ~/Docker/volumes/pgadmin4:/var/lib/pgadmin4/data
        networks:
            - kids-wallet

networks:
    kids-wallet:
