# curl -X 'GET' 
#  'http://localhost:5164/accounts/643485ab-3915-4464-9efa-b26722750994' 
#  -H 'accept: */*'
GET {{scheme}}://{{host}}/{{version}}/accounts/643485ab-3915-4464-9efa-b26722750994
accept: */*

###

# curl -X 'GET' 
#  'http://localhost:5164/accounts' 
#  -H 'accept: */*'
GET {{scheme}}://{{host}}/{{version}}/accounts
accept: */*

###

# curl -X 'POST' 
#  'http://localhost:5164/accounts' 
#  -H 'accept: */*' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "accountId": "643485ab-3915-4464-9efa-b26722750994",
#  "name": "Example",
#  "balance": 10000,
#  "kidWalletId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
#}'
POST {{scheme}}://{{host}}/{{version}}/accounts
accept: */*
Content-Type: application/json

{
  "kidAccountId": "643485ab-3915-4464-9efa-b26722750994",
  "name": "Example",
  "balance": 10000,
  "kidWalletId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

###

# curl -X 'PUT' 
#  'http://localhost:5164/accounts/643485ab-3915-4464-9efa-b26722750994' 
#  -H 'accept: */*' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
#  "name": "Example-10",
#  "balance": 25000
#}'
PUT {{scheme}}://{{host}}/{{version}}/accounts/643485ab-3915-4464-9efa-b26722750994
accept: */*
Content-Type: application/json

{
  "kidAccountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "Example-10",
  "balance": 25000
}

###

# curl -X 'DELETE' 
#  'http://localhost:5164/accounts/643485ab-3915-4464-9efa-b26722750994' 
#  -H 'accept: */*'
DELETE {{scheme}}://{{host}}/{{version}}/accounts/643485ab-3915-4464-9efa-b26722750994
accept: */*
