name: audit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
