name: deploy
on:
  push:
    branches: [main, dev]
    paths:
      - Src/**

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: [trivy, code-ql]
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  buid-and-push-docker-image-to-ghcr:
    needs: test
    uses: ./.github/workflows/reusable-build&push_docker_image.yml
    with:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.actor }}/kids-wallet-api
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
