name: pull-request
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - Src/**

permissions:
  actions: read
  packages: write
  contents: write
  id-token: write
  checks: write
  security-events: write

jobs:
  sanity:
    uses: ./.github/workflows/reusable-sanity.yml

  code-ql:
    uses: ./.github/workflows/reusable-code-ql.yml
    needs: sanity

  trivy:
    uses: ./.github/workflows/reusable-trivy.yml
    needs: sanity

  test:
    uses: ./.github/workflows/reusable-test.yml
    needs: [trivy, code-ql]
    secrets:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}