name: test
on:
  workflow_dispatch:
  workflow_call:
env:
  DOTNET_VERSION: "8.0.x"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: https://nuget.pkg.github.com/piotrkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore 

      - name: Tests
        run: dotnet test --no-build --settings tests.runsettings --results-directory "TestResults" --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults

      - name: Tests report generation
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test-results (${{ env.DOTNET_VERSION }})
          path: "TestResults/*.trx"
          reporter: dotnet-trx
          list-tests: "failed"
